// Generated by Lasy AI - https://lasy.ai
import type { Metadata } from "next";
import Script from "next/script";
import "./globals.css";
// Import all available fonts for AI usage
import "../lib/fonts";

export const metadata: Metadata = {
  title: "Dr. João Pedro do Carmo Dutra - Neuropsicólogo | TDAH e Autismo no Adulto",
  description: "Transforme sua mente. Redescubra sua vida. Neuropsicólogo especialista em TDAH e Autismo no Adulto. Método, técnica e caminho claro para recuperar foco, equilíbrio e sentido. CRP 06175783",
  keywords: "neuropsicólogo, TDAH adulto, autismo adulto, psicologia, neuropsicologia, São Carlos, terapia cognitivo comportamental, psicanálise, psicopedagogia, João Pedro do Carmo Dutra",
  authors: [{ name: "Dr. João Pedro do Carmo Dutra" }],
  openGraph: {
    title: "Dr. João Pedro do Carmo Dutra - Transforme sua mente. Redescubra sua vida.",
    description: "Neuropsicólogo especialista em TDAH e Autismo no Adulto. Pare de conviver com sintomas que roubam seu foco, suas relações e sua energia.",
    type: "website",
    locale: "pt_BR",
    siteName: "Dr. João Pedro do Carmo Dutra",
  },
  twitter: {
    card: "summary_large_image",
    title: "Dr. João Pedro do Carmo Dutra - Neuropsicólogo",
    description: "Especialista em TDAH e Autismo no Adulto. Transforme sua mente, redescubra sua vida.",
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
    },
  },
  verification: {
    google: "google-site-verification-code-here",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <head>
        <Script src="/lasy-bridge.js" strategy="beforeInteractive" />
        <link rel="canonical" href="https://drjoaopedro.com.br" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="theme-color" content="#0A1A2F" />
        <meta name="format-detection" content="telephone=no" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="default" />
      </head>
      <body className="font-geist-sans antialiased">
        {children}
      </body>
    </html>
  );
}